#!/usr/bin/env bash
ROOT_DIR="$(git rev-parse --show-toplevel)"

trap 'popd > /dev/null' EXIT

pushd "${ROOT_DIR}" > /dev/null
while read -r file; do
	if [[ "${file}" == *.py ]]; then
		black -l 120 "${file}"
		git add "${file}"
	fi
done <<< "$(git diff --cached --name-only --diff-filter=ACM)"
